create extension if not exists pgcrypto;
create extension if not exists postgis;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function public.geojson_to_linestring(payload jsonb)
returns geometry(LineString, 4326)
language sql
immutable
as $$
  select case
    when payload is null then null
    else st_setsrid(st_geomfromgeojson(payload::text), 4326)::geometry(LineString, 4326)
  end;
$$;

create or replace function public.telemetry_to_point(lat double precision, lon double precision)
returns geometry(Point, 4326)
language sql
immutable
as $$
  select st_setsrid(st_makepoint(lon, lat), 4326)::geometry(Point, 4326);
$$;

create table if not exists public.route_templates (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  install_id text not null,
  name text not null,
  is_closed boolean not null default false,
  raw_geometry jsonb not null,
  raw_geometry_geom geometry(LineString, 4326),
  snapped_geometry jsonb,
  snapped_geometry_geom geometry(LineString, 4326),
  start_finish_gate jsonb not null,
  start_finish_gate_geom geometry(LineString, 4326),
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sectors (
  id uuid primary key,
  route_template_id uuid not null references public.route_templates (id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  display_order integer not null,
  label text not null,
  gate_geometry jsonb not null,
  gate_geometry_geom geometry(LineString, 4326),
  direction_hint text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.session_runs (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  route_template_id uuid not null references public.route_templates (id) on delete cascade,
  install_id text not null,
  status text not null check (status in ('draft', 'recording', 'completed', 'synced')),
  started_at timestamptz not null,
  ended_at timestamptz not null,
  distance_m double precision not null,
  max_speed_kmh double precision not null,
  avg_speed_kmh double precision not null,
  lap_summaries jsonb not null default '[]'::jsonb,
  sector_summaries jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.telemetry_points (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  session_run_id uuid not null references public.session_runs (id) on delete cascade,
  timestamp timestamptz not null,
  latitude double precision not null,
  longitude double precision not null,
  position_geom geometry(Point, 4326),
  speed_mps double precision not null,
  accuracy_m double precision not null,
  heading_deg double precision not null,
  altitude_m double precision,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists route_templates_user_idx on public.route_templates (user_id, created_at desc);
create index if not exists sectors_route_idx on public.sectors (route_template_id, display_order);
create index if not exists session_runs_user_idx on public.session_runs (user_id, created_at desc);
create index if not exists telemetry_points_session_idx on public.telemetry_points (session_run_id, timestamp);
create index if not exists route_templates_raw_geom_idx on public.route_templates using gist (raw_geometry_geom);
create index if not exists route_templates_snapped_geom_idx on public.route_templates using gist (snapped_geometry_geom);
create index if not exists route_templates_gate_geom_idx on public.route_templates using gist (start_finish_gate_geom);
create index if not exists sectors_gate_geom_idx on public.sectors using gist (gate_geometry_geom);
create index if not exists telemetry_points_geom_idx on public.telemetry_points using gist (position_geom);

create or replace function public.sync_route_template_geometries()
returns trigger
language plpgsql
as $$
begin
  new.raw_geometry_geom = public.geojson_to_linestring(new.raw_geometry);
  new.snapped_geometry_geom = public.geojson_to_linestring(new.snapped_geometry);
  new.start_finish_gate_geom = public.geojson_to_linestring(new.start_finish_gate);
  return new;
end;
$$;

create or replace function public.sync_sector_geometries()
returns trigger
language plpgsql
as $$
begin
  new.gate_geometry_geom = public.geojson_to_linestring(new.gate_geometry);
  return new;
end;
$$;

create or replace function public.sync_telemetry_geometries()
returns trigger
language plpgsql
as $$
begin
  new.position_geom = public.telemetry_to_point(new.latitude, new.longitude);
  return new;
end;
$$;

drop trigger if exists route_templates_sync_geometry on public.route_templates;
create trigger route_templates_sync_geometry
before insert or update on public.route_templates
for each row
execute procedure public.sync_route_template_geometries();

drop trigger if exists sectors_sync_geometry on public.sectors;
create trigger sectors_sync_geometry
before insert or update on public.sectors
for each row
execute procedure public.sync_sector_geometries();

drop trigger if exists telemetry_points_sync_geometry on public.telemetry_points;
create trigger telemetry_points_sync_geometry
before insert or update on public.telemetry_points
for each row
execute procedure public.sync_telemetry_geometries();

drop trigger if exists route_templates_set_updated_at on public.route_templates;
create trigger route_templates_set_updated_at
before update on public.route_templates
for each row
execute procedure public.set_updated_at();

drop trigger if exists sectors_set_updated_at on public.sectors;
create trigger sectors_set_updated_at
before update on public.sectors
for each row
execute procedure public.set_updated_at();

drop trigger if exists session_runs_set_updated_at on public.session_runs;
create trigger session_runs_set_updated_at
before update on public.session_runs
for each row
execute procedure public.set_updated_at();

alter table public.route_templates enable row level security;
alter table public.sectors enable row level security;
alter table public.session_runs enable row level security;
alter table public.telemetry_points enable row level security;

drop policy if exists "route_templates_owner_policy" on public.route_templates;
create policy "route_templates_owner_policy"
on public.route_templates
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "sectors_owner_policy" on public.sectors;
create policy "sectors_owner_policy"
on public.sectors
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "session_runs_owner_policy" on public.session_runs;
create policy "session_runs_owner_policy"
on public.session_runs
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "telemetry_points_owner_policy" on public.telemetry_points;
create policy "telemetry_points_owner_policy"
on public.telemetry_points
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
